# Generated by Django 6.0.1 on 2026-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='post_type',
            field=models.CharField(choices=[('SENDER', 'Sender'), ('COURIER', 'Courier')], default='SENDER', max_length=10),
        ),
    ]
