# Generated by Django 6.0.1 on 2026-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobposting_destination_jobposting_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='post_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('COURIER', 'Courier')], default='CUSTOMER', max_length=10),
        ),
    ]
